# Generated by Django 4.1 on 2024-07-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artist", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriteartist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.buyerprofile",
                verbose_name="Поклонник автора",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteartist",
            constraint=models.UniqueConstraint(
                fields=("artist", "user"), name="unique_favorite_artist"
            ),
        ),
    ]
