volumes:
  pg_data:
  backend_static:

services:

  backend:
    container_name: backend_container
    build: ../poetry-sagaart
    restart: always
    env_file: .env
    volumes:
      - backend_static:/backend_static
    depends_on:
      - db

  db:
    container_name: database_container
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    container_name: nginx_container
    image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - backend_static:/staticfiles/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
