# Generated by Django 4.1 on 2024-07-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("artshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylebuyerprofile",
            name="buyer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.buyerprofile"
            ),
        ),
        migrations.AddField(
            model_name="stylebuyerprofile",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artshop.style"
            ),
        ),
        migrations.AddField(
            model_name="categorybuyerprofile",
            name="buyer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.buyerprofile"
            ),
        ),
        migrations.AddField(
            model_name="categorybuyerprofile",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="artshop.category"
            ),
        ),
    ]
