# Generated by Django 4.1 on 2024-07-03 09:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artist", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("artshop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("password", models.CharField(max_length=150, verbose_name="password")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("moderator", "Moderator"),
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(6)],
                        verbose_name="email",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="BuyerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="buyer_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("surname", models.CharField(max_length=150, verbose_name="surname")),
                (
                    "patronymic_surname",
                    models.CharField(max_length=150, verbose_name="patronymic_surname"),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Enter phone number", max_length=20),
                ),
                (
                    "favorite_style",
                    models.CharField(max_length=50, verbose_name="favorite_style"),
                ),
                (
                    "favorite_category",
                    models.CharField(max_length=50, verbose_name="favorite_category"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users_photos/",
                        verbose_name="аватар",
                    ),
                ),
                (
                    "favorite_artists",
                    models.ManyToManyField(
                        through="artist.FavoriteArtist",
                        to="artist.artist",
                        verbose_name="Любимые художники",
                    ),
                ),
                (
                    "favorite_categories",
                    models.ManyToManyField(
                        through="artshop.CategoryBuyerProfile",
                        to="artshop.category",
                        verbose_name="Любимые категории",
                    ),
                ),
                (
                    "favorite_styles",
                    models.ManyToManyField(
                        through="artshop.StyleBuyerProfile",
                        to="artshop.style",
                        verbose_name="Любимые стили",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="seller_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("surname", models.CharField(max_length=150, verbose_name="surname")),
                (
                    "patronymic_surname",
                    models.CharField(max_length=150, verbose_name="patronymic_surname"),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Enter phone number", max_length=20),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users_photos/",
                        verbose_name="аватар",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("auto_renewal", models.BooleanField(default=False)),
                ("duration", models.IntegerField()),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="users.buyerprofile",
                        verbose_name="подписчик",
                    ),
                ),
            ],
        ),
    ]
